### ISSUE TITLE
Use Shopify eslint

### ISSUE THREAD

**Issue by cartogram** [DougEdey/Elsinore_Web#5]
I think it would simply your linter setup if you used the Shopify one. I am biased, but I think it is really good. 

- Remove all the eslint plugin dependencies you have installed (just keep the `eslint` main lib). 
- Install the shopify lib

```
yarn add --dev @shopify/eslint-plugin
```

- change you eslintrc.js to look like:

```
module.exports = {
  extends: [
    'plugin:@shopify/esnext',
    'plugin:@shopify/react',
    'plugin:@shopify/node',
    'plugin:@shopify/prettier',
  ],
};
```

https://github.com/Shopify/web-configs/tree/main/packages/eslint-plugin

**Comment by DougEdey** [comment]
What's your thoughts on the `react/react-in-jsx-scope`? Should I keep that rule or ignore it since next.js doesn't need it?
